#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 0
#define VERSION_MINOR 0
#define VERSION_MICRO 1
#define VERSION_SPECIAL "/beta"


#define STRINGIFY0(s) # s
#define STRINGIFY(s) STRINGIFY0(s)

#define _VERSION STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR) "." STRINGIFY(VERSION_MICRO) "" VERSION_SPECIAL

#endif // VERSION_H
